language: python
python:
  - "3.5"

sudo: required 

before_install: 
- sudo pip install flake8

script:
- cd exercise_sheet_01 && make all
- cd ../exercise_sheet_02 && make all
- cd ../exercise_sheet_05 && make all